# Generated by Django 5.0.6 on 2025-09-03 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('app_type', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('BOTH', 'Both')], default='ANDROID', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANALYSIS_PENDING', 'Analysis Pending'), ('ANALYSIS_COMPLETE', 'Analysis Complete'), ('DESIGN_PENDING', 'Design Pending'), ('DESIGN_COMPLETE', 'Design Complete'), ('CODE_GENERATION', 'Code Generation'), ('QA_PENDING', 'QA Pending'), ('QA_COMPLETE', 'QA Complete'), ('DEPLOYMENT_PENDING', 'Deployment Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('user_persona_document', models.TextField(blank=True, null=True)),
                ('brand_palette', models.JSONField(blank=True, null=True)),
                ('generated_code_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
