# Generated by Django 5.0.6 on 2025-09-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployment_option',
            field=models.CharField(choices=[('NOT_CHOSEN', 'Not Chosen'), ('AMAZON_S3', 'Amazon S3'), ('GOOGLE_PLAY', 'Google Play Store'), ('APP_STORE', 'Apple App Store')], default='NOT_CHOSEN', max_length=20),
        ),
    ]
